"""
moduleB.py
Module B: Personalized Edit Recommendation Engine

Pipeline
--------
1. Load (LLM draft, post-edited final) pairs -> treatment responses only
2. Sentence-level alignment (difflib)
3. Edit-type extraction (rule-based deltas)
4. Per-user edit profile
5. Logistic Regression recommender
6. Evaluation
7. Editor archetypes using KMeans
8. Frequent word substitutions

IMPORTANT
---------
The LLM-associated vocabulary is NOT hand-written here.

It is generated by B.py and loaded from:
    ai_lexicon.txt

Usage
-----
pip install pandas numpy scipy scikit-learn joblib

python moduleB.py \
    --data dataset \
    --out results_b \
    --lexicon lexicon/ai_lexicon.txt
"""

import argparse
import glob
import json
import os
import re
import difflib
from collections import Counter

import numpy as np
import pandas as pd

from sklearn.cluster import KMeans
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GroupKFold
from sklearn.preprocessing import StandardScaler


# ================================================================
# 1. CONFIGURATION
# ================================================================

EDITED_THRESHOLD = 0.90

TOP_K = 3

LONG_SENTENCE_WORDS = 20


# ----------------------------------------------------------------
# IMPORTANT:
# This starts empty.
# B.py -> ai_lexicon.txt -> loaded into this set in main()
# ----------------------------------------------------------------
AI_LEXICON = set()


EDIT_TYPES = [
    "em_dash_removed",
    "contraction_added",
    "shortened",
    "lengthened",
    "ai_word_removed",
    "simplified_words",
    "first_person_added",
    "exclamation_added",
    "punctuation_changed",
    "rewritten",
    "deleted",
]


SUGGESTION = {
    "em_dash_removed":
        "Replace the em dash with a comma, period, or 'and'.",

    "contraction_added":
        "Use contractions (do not -> don't, I am -> I'm).",

    "shortened":
        "Shorten or split this sentence.",

    "ai_word_removed":
        "Swap the LLM-associated word for a simpler, more natural word.",

    "simplified_words":
        "Replace long or formal words with everyday ones.",

    "first_person_added":
        "Make it more personal by adding I, my, or a specific detail.",

    "exclamation_added":
        "Add energy if that matches how you would naturally say it.",

    "rewritten":
        "Rewrite this sentence in your own words.",
}


# ================================================================
# 2. LOAD DATA
# ================================================================

def normalize_text(x):
    """
    Normalize text and convert curly quotes to straight quotes.
    """

    if x is None:
        return ""

    return (
        str(x)
        .replace("\u2019", "'")
        .replace("\u2018", "'")
        .replace("\u201c", '"')
        .replace("\u201d", '"')
        .strip()
    )


def load_pairs(folder):
    """
    Load treatment responses only.

    Treatment:
        model_generation_shown == 1

    Returns:
        pid
        doc_id
        scenario
        draft
        final
    """

    rows = []

    files = sorted(
        glob.glob(
            os.path.join(folder, "*.json")
        )
    )

    print("JSON files found:", len(files))

    for fp in files:

        try:

            with open(
                fp,
                "r",
                encoding="utf-8"
            ) as f:

                data = json.load(f)

        except Exception as e:

            print(
                "Skipping invalid JSON:",
                fp,
                "|",
                e
            )

            continue

        user_info = data.get(
            "user_info",
            {}
        )

        pid = user_info.get("id")

        if pid is None:

            print(
                "Skipping file without participant ID:",
                fp
            )

            continue

        responses = data.get(
            "responses",
            {}
        )

        for rid, response in responses.items():

            # ----------------------------------------------------
            # Some malformed responses may not contain this field.
            # ----------------------------------------------------

            shown = response.get(
                "model_generation_shown"
            )

            if shown is None:
                continue

            try:
                shown = int(shown)
            except (TypeError, ValueError):
                continue

            # Only treatment responses
            if shown != 1:
                continue

            draft = normalize_text(
                response.get(
                    "model_generation"
                )
            )

            final = normalize_text(
                response.get(
                    "final_version"
                )
            )

            if not draft or not final:
                continue

            scenario = response.get(
                "scenario",
                "unknown"
            )

            rows.append(
                {
                    "pid": pid,
                    "doc_id": f"{pid}_{rid}",
                    "scenario": scenario,
                    "draft": draft,
                    "final": final,
                }
            )

    return pd.DataFrame(rows)


# ================================================================
# 3. SENTENCE SPLITTING
# ================================================================

def split_sentences(text):
    """
    Split text into sentences using ., !, ?, or newline.
    """

    if not text:
        return []

    parts = re.split(
        r"(?<=[.!?])\s+|\n+",
        text.strip()
    )

    return [
        p.strip()
        for p in parts
        if p and p.strip()
    ]


def toks(s):
    """
    Tokenize words and punctuation.
    """

    return re.findall(
        r"\w+(?:'\w+)?|[^\w\s]",
        s.lower()
    )


# ================================================================
# 4. SENTENCE ALIGNMENT
# ================================================================

def align_sentences(
    draft_sents,
    final_sents
):
    """
    Greedy one-to-one sentence alignment.

    Each final sentence can be matched to at most one
    draft sentence.

    Returns:
        [(matched_final_sentence, similarity), ...]
    """

    output = []

    final_tokens = [
        toks(sentence)
        for sentence in final_sents
    ]

    used = set()

    for draft_sentence in draft_sents:

        draft_tokens = toks(
            draft_sentence
        )

        best_idx = None
        best_ratio = 0.0

        for j, final_tokens_j in enumerate(
            final_tokens
        ):

            if j in used:
                continue

            ratio = difflib.SequenceMatcher(
                None,
                draft_tokens,
                final_tokens_j,
                autojunk=False
            ).ratio()

            if ratio > best_ratio:

                best_ratio = ratio
                best_idx = j

        if best_idx is None:

            output.append(
                (None, 0.0)
            )

        else:

            used.add(best_idx)

            output.append(
                (
                    final_sents[best_idx],
                    best_ratio
                )
            )

    return output


# ================================================================
# 5. SENTENCE STATISTICS
# ================================================================

UNCONTRACTED = re.compile(
    r"\b("
    r"do not|does not|did not|is not|are not|was not|were not|"
    r"cannot|can not|will not|would not|could not|should not|"
    r"have not|has not|had not|i am|i will|i have|i would|"
    r"it is|that is|there is|we are|you are|they are|let us"
    r")\b",
    re.I
)


CONTRACTION = re.compile(
    r"\b\w+'(?:t|s|re|ve|ll|d|m)\b",
    re.I
)


def stats_of(s):
    """
    Extract sentence-level features.
    """

    words = re.findall(
        r"[A-Za-z']+",
        s.lower()
    )

    n = max(
        len(words),
        1
    )

    return {
        "n_words":
            len(words),

        "n_dash":
            s.count("—") + s.count("–"),

        "n_contr":
            len(
                CONTRACTION.findall(s)
            ),

        "n_uncontr":
            len(
                UNCONTRACTED.findall(s)
            ),

        # IMPORTANT:
        # These words come from B.py's data-driven lexicon.
        "ai_hits":
            sum(
                word in AI_LEXICON
                for word in words
            ),

        "long_frac":
            sum(
                len(word) >= 9
                for word in words
            ) / n,

        "avg_wlen":
            float(
                np.mean(
                    [
                        len(word)
                        for word in words
                    ]
                )
            ) if words else 0.0,

        "fp":
            sum(
                word in {
                    "i",
                    "my",
                    "me",
                    "i'm",
                    "i've",
                    "i'll",
                    "mine",
                }
                for word in words
            ),

        "n_excl":
            s.count("!"),

        "n_comma":
            s.count(","),

        "n_semi":
            s.count(";") + s.count(":"),
    }


# ================================================================
# 6. EDIT-TYPE EXTRACTION
# ================================================================

def edit_types(
    draft_sentence,
    final_sentence,
    ratio
):
    """
    Determine HOW the draft sentence was changed.

    These labels are rule-based / heuristic.
    """

    flags = {
        edit_type: 0
        for edit_type in EDIT_TYPES
    }

    # ------------------------------------------------------------
    # Very low similarity = deletion / complete replacement
    # ------------------------------------------------------------

    if (
        final_sentence is None
        or ratio < 0.30
    ):

        flags["deleted"] = 1

        return flags

    a = stats_of(
        draft_sentence
    )

    b = stats_of(
        final_sentence
    )

    # ------------------------------------------------------------
    # Specific edit types
    # ------------------------------------------------------------

    flags["em_dash_removed"] = int(
        a["n_dash"] > b["n_dash"]
    )

    flags["contraction_added"] = int(
        b["n_contr"] > a["n_contr"]
    )

    flags["shortened"] = int(
        b["n_words"]
        <=
        0.8 * max(
            a["n_words"],
            1
        )
    )

    flags["lengthened"] = int(
        b["n_words"]
        >=
        1.2 * max(
            a["n_words"],
            1
        )
    )

    flags["ai_word_removed"] = int(
        b["ai_hits"]
        <
        a["ai_hits"]
    )

    flags["simplified_words"] = int(
        b["long_frac"]
        <
        a["long_frac"] - 0.02
        and
        b["avg_wlen"]
        <
        a["avg_wlen"]
    )

    flags["first_person_added"] = int(
        b["fp"]
        >
        a["fp"]
    )

    flags["exclamation_added"] = int(
        b["n_excl"]
        >
        a["n_excl"]
    )

    flags["punctuation_changed"] = int(
        (
            b["n_comma"],
            b["n_semi"]
        )
        !=
        (
            a["n_comma"],
            a["n_semi"]
        )
    )

    flags["rewritten"] = int(
        ratio < 0.50
    )

    return flags


# ================================================================
# 7. BUILD SENTENCE TABLE
# ================================================================

def build_sentence_table(
    pairs
):

    rows = []

    substitutions = Counter()

    for _, p in pairs.iterrows():

        draft_sentences = split_sentences(
            p.draft
        )

        final_sentences = split_sentences(
            p.final
        )

        aligned = align_sentences(
            draft_sentences,
            final_sentences
        )

        total_sentences = len(
            draft_sentences
        )

        for i, (
            (final_sentence, ratio),
            draft_sentence
        ) in enumerate(
            zip(
                aligned,
                draft_sentences
            )
        ):

            edited = int(
                ratio < EDITED_THRESHOLD
            )

            row = {
                "pid":
                    p.pid,

                "doc_id":
                    p.doc_id,

                "scenario":
                    p.scenario,

                "sent_idx":
                    i,

                "rel_pos":
                    i /
                    max(
                        total_sentences - 1,
                        1
                    ),

                "n_sents":
                    total_sentences,

                "sentence":
                    draft_sentence,

                "matched_final":
                    final_sentence,

                "match_ratio":
                    ratio,

                "edited":
                    edited,
            }

            # Sentence features
            row.update(
                stats_of(
                    draft_sentence
                )
            )

            # Edit-type labels
            row.update(
                {
                    f"et_{key}": value
                    for key, value
                    in edit_types(
                        draft_sentence,
                        final_sentence,
                        ratio
                    ).items()
                }
            )

            rows.append(row)

            # ----------------------------------------------------
            # Frequent word substitutions
            # ----------------------------------------------------

            if (
                final_sentence is not None
                and
                0.30 <= ratio < 1.0
            ):

                a = toks(
                    draft_sentence
                )

                b = toks(
                    final_sentence
                )

                matcher = difflib.SequenceMatcher(
                    None,
                    a,
                    b,
                    autojunk=False
                )

                for (
                    tag,
                    i1,
                    i2,
                    j1,
                    j2
                ) in matcher.get_opcodes():

                    if (
                        tag == "replace"
                        and
                        (i2 - i1) <= 2
                        and
                        (j2 - j1) <= 2
                    ):

                        substitutions[
                            (
                                " ".join(
                                    a[i1:i2]
                                ),
                                " ".join(
                                    b[j1:j2]
                                )
                            )
                        ] += 1

                    elif (
                        tag == "delete"
                        and
                        (i2 - i1) == 1
                    ):

                        substitutions[
                            (
                                a[i1],
                                "<deleted>"
                            )
                        ] += 1

    return (
        pd.DataFrame(rows),
        substitutions
    )


# ================================================================
# 8. USER EDITING PROFILES
# ================================================================

def make_profile(
    sentence_rows
):
    """
    Compute a user's editing tendencies.
    """

    if (
        sentence_rows is None
        or
        len(sentence_rows) == 0
    ):

        return {
            f"prof_{edit_type}": 0.0
            for edit_type in EDIT_TYPES
        } | {
            "prof_edit_rate": 0.0
        }

    profile = {
        f"prof_{edit_type}":
            float(
                sentence_rows[
                    f"et_{edit_type}"
                ].mean()
            )
        for edit_type in EDIT_TYPES
    }

    profile["prof_edit_rate"] = float(
        sentence_rows[
            "edited"
        ].mean()
    )

    return profile


def attach_profiles(
    tab
):
    """
    Leave-one-document-out profile.

    For each document:
        profile = user's OTHER documents
    """

    output = []

    for pid, group in tab.groupby(
        "pid"
    ):

        for doc_id, doc_group in group.groupby(
            "doc_id"
        ):

            history = group[
                group.doc_id != doc_id
            ]

            profile = make_profile(
                history
            )

            output.append(
                doc_group.assign(
                    **profile
                )
            )

    if not output:
        return tab.copy()

    return pd.concat(
        output
    ).sort_index()


# ================================================================
# 9. MODEL FEATURES
# ================================================================

BASE_FEATURES = [
    "n_words",
    "n_dash",
    "n_contr",
    "n_uncontr",
    "ai_hits",
    "long_frac",
    "avg_wlen",
    "fp",
    "n_excl",
    "n_comma",
    "n_semi",
    "rel_pos",
]


def feature_frame(
    table,
    personalized
):

    X = table[
        BASE_FEATURES
    ].copy()

    if personalized:

        # Sentence trigger × user preference

        X["x_dash"] = (
            (table.n_dash > 0)
            .astype(float)
            *
            table.prof_em_dash_removed
        )

        X["x_contr"] = (
            (table.n_uncontr > 0)
            .astype(float)
            *
            table.prof_contraction_added
        )

        X["x_short"] = (
            (
                table.n_words
                >=
                LONG_SENTENCE_WORDS
            )
            .astype(float)
            *
            table.prof_shortened
        )

        X["x_ai"] = (
            (table.ai_hits > 0)
            .astype(float)
            *
            table.prof_ai_word_removed
        )

        X["x_simple"] = (
            table.long_frac
            *
            table.prof_simplified_words
        )

        X["x_fp"] = (
            (table.fp == 0)
            .astype(float)
            *
            table.prof_first_person_added
        )

        X["x_excl"] = (
            (table.n_excl == 0)
            .astype(float)
            *
            table.prof_exclamation_added
        )

        X["x_rewrite"] = (
            table.prof_rewritten
        )

        X["prof_edit_rate"] = (
            table.prof_edit_rate
        )

    return X.astype(float)


# ================================================================
# 10. TRAIN LOGISTIC REGRESSION
# ================================================================

def fit_model(
    table,
    personalized
):

    X = feature_frame(
        table,
        personalized
    )

    y = table[
        "edited"
    ].astype(int)

    if y.nunique() < 2:

        raise ValueError(
            "Logistic Regression requires "
            "both edited and unedited examples."
        )

    scaler = StandardScaler()

    X_scaled = scaler.fit_transform(
        X
    )

    model = LogisticRegression(
        max_iter=2000,
        class_weight="balanced",
        C=0.5,
        random_state=0
    )

    model.fit(
        X_scaled,
        y
    )

    return (
        scaler,
        model,
        list(X.columns)
    )


def predict(
    model,
    table,
    personalized
):

    scaler, lr, _ = model

    X = feature_frame(
        table,
        personalized
    )

    return lr.predict_proba(
        scaler.transform(X)
    )[:, 1]


# ================================================================
# 11. RANKING METRICS
# ================================================================

def precision_at_k(
    y,
    scores,
    k
):

    order = np.argsort(
        -scores
    )[:k]

    return float(
        y[order].mean()
    )


def recall_at_k(
    y,
    scores,
    k
):

    total_relevant = y.sum()

    if total_relevant == 0:
        return np.nan

    order = np.argsort(
        -scores
    )[:k]

    return float(
        y[order].sum()
        /
        total_relevant
    )


def ndcg_at_k(
    y,
    scores,
    k
):

    order = np.argsort(
        -scores
    )[:k]

    dcg = sum(
        y[i]
        /
        np.log2(rank + 2)

        for rank, i
        in enumerate(order)
    )

    ideal = sorted(
        y,
        reverse=True
    )[:k]

    idcg = sum(
        value
        /
        np.log2(rank + 2)

        for rank, value
        in enumerate(ideal)
    )

    if idcg == 0:
        return np.nan

    return float(
        dcg / idcg
    )


def doc_metrics(
    table,
    score_col,
    k=TOP_K
):

    precisions = []
    recalls = []
    ndcgs = []

    for _, group in table.groupby(
        "doc_id"
    ):

        y = group[
            "edited"
        ].to_numpy()

        scores = group[
            score_col
        ].to_numpy()

        if y.sum() == 0:
            continue

        precisions.append(
            precision_at_k(
                y,
                scores,
                k
            )
        )

        recalls.append(
            recall_at_k(
                y,
                scores,
                k
            )
        )

        ndcgs.append(
            ndcg_at_k(
                y,
                scores,
                k
            )
        )

    return (
        np.mean(precisions)
        if precisions
        else np.nan,

        np.mean(recalls)
        if recalls
        else np.nan,

        np.nanmean(ndcgs)
        if ndcgs
        else np.nan
    )


# ================================================================
# 12. PARTICIPANT-DISJOINT EVALUATION
# ================================================================

def evaluate_participant_disjoint(
    tab,
    n_splits=5,
    seed=0
):
    """
    Participant-disjoint evaluation.

    Participants in the test fold are completely unseen
    during training.

    Therefore this measures generalization to unseen users.

    Personalization is NOT available for completely new users.
    """

    table = tab.copy().reset_index(
        drop=True
    )

    rng = np.random.default_rng(
        seed
    )

    table["s_random"] = rng.random(
        len(table)
    )

    table["s_global"] = np.nan

    n_splits = min(
        n_splits,
        table.pid.nunique()
    )

    splitter = GroupKFold(
        n_splits=n_splits
    )

    for train_idx, test_idx in splitter.split(
        table,
        groups=table.pid
    ):

        train = table.iloc[
            train_idx
        ]

        test = table.iloc[
            test_idx
        ]

        if train["edited"].nunique() < 2:
            continue

        model = fit_model(
            train,
            personalized=False
        )

        table.loc[
            test_idx,
            "s_global"
        ] = predict(
            model,
            test,
            personalized=False
        )

    rows = []

    for name, column in [
        ("random", "s_random"),
        ("non-personalized", "s_global"),
    ]:

        scored = table.dropna(
            subset=[column]
        )

        if (
            len(scored) > 0
            and
            scored.edited.nunique() > 1
        ):

            auc = roc_auc_score(
                scored.edited,
                scored[column]
            )

        else:

            auc = np.nan

        precision, recall, ndcg = (
            doc_metrics(
                scored,
                column
            )
        )

        rows.append(
            {
                "model":
                    name,

                "n_sentences":
                    len(scored),

                "AUROC":
                    auc,

                f"P@{TOP_K}":
                    precision,

                f"Recall@{TOP_K}":
                    recall,

                f"NDCG@{TOP_K}":
                    ndcg,
            }
        )

    return (
        pd.DataFrame(rows),
        table
    )


# ================================================================
# 13. WARM-START PERSONALIZATION
# ================================================================

def evaluate_warm_start(
    tab,
    n_splits=5,
    seed=0
):
    """
    Warm-start personalization evaluation.

    The same participant can appear in training and testing,
    but a test document's user profile is built only from
    OTHER historical documents.

    This represents the actual personalized use case:
        "We have previous writing/editing behavior from this user."
    """

    rng = np.random.default_rng(
        seed
    )

    table = tab.copy().reset_index(
        drop=True
    )

    table["s_random"] = rng.random(
        len(table)
    )

    table["s_global"] = np.nan
    table["s_personal"] = np.nan

    # ------------------------------------------------------------
    # Assign documents to folds within each participant
    # ------------------------------------------------------------

    documents = (
        table[
            ["pid", "doc_id"]
        ]
        .drop_duplicates()
        .reset_index(drop=True)
    )

    documents["fold"] = -1

    for pid, indices in documents.groupby(
        "pid"
    ).groups.items():

        indices = list(indices)

        rng.shuffle(
            indices
        )

        for position, row_idx in enumerate(
            indices
        ):

            documents.loc[
                row_idx,
                "fold"
            ] = (
                position
                %
                n_splits
            )

    table = table.merge(
        documents,
        on=[
            "pid",
            "doc_id"
        ],
        how="left"
    )

    # ------------------------------------------------------------
    # Fold evaluation
    # ------------------------------------------------------------

    for fold in range(
        n_splits
    ):

        train = table[
            table["fold"] != fold
        ].copy()

        test = table[
            table["fold"] == fold
        ].copy()

        if (
            len(train) == 0
            or
            len(test) == 0
        ):
            continue

        if train["edited"].nunique() < 2:
            continue

        # --------------------------------------------------------
        # Global model
        # --------------------------------------------------------

        global_model = fit_model(
            train,
            personalized=False
        )

        table.loc[
            test.index,
            "s_global"
        ] = predict(
            global_model,
            test,
            personalized=False
        )

        # --------------------------------------------------------
        # Training participant profiles
        # --------------------------------------------------------

        train_profiles = {}

        for pid, group in train.groupby(
            "pid"
        ):

            train_profiles[pid] = make_profile(
                group
            )

        # --------------------------------------------------------
        # Personalized training data
        #
        # Each training document gets a profile based on
        # the participant's OTHER training documents.
        # --------------------------------------------------------

        personalized_train = []

        for pid, group in train.groupby(
            "pid"
        ):

            for doc_id, doc_group in group.groupby(
                "doc_id"
            ):

                history = group[
                    group.doc_id != doc_id
                ]

                profile = make_profile(
                    history
                )

                personalized_train.append(
                    doc_group.assign(
                        **profile
                    )
                )

        if not personalized_train:
            continue

        personalized_train = pd.concat(
            personalized_train
        )

        if (
            personalized_train[
                "edited"
            ].nunique()
            <
            2
        ):
            continue

        # --------------------------------------------------------
        # Personalized model
        # --------------------------------------------------------

        personal_model = fit_model(
            personalized_train,
            personalized=True
        )

        # --------------------------------------------------------
        # Build profiles for test documents using ONLY
        # historical training documents.
        # --------------------------------------------------------

        test_personal = test.copy()

        profile_rows = []

        for pid in test_personal.pid:

            profile_rows.append(
                train_profiles.get(
                    pid,
                    make_profile(
                        pd.DataFrame()
                    )
                )
            )

        profile_df = pd.DataFrame(
            profile_rows,
            index=test_personal.index
        )

        for column in profile_df.columns:

            test_personal[
                column
            ] = profile_df[column]

        table.loc[
            test.index,
            "s_personal"
        ] = predict(
            personal_model,
            test_personal,
            personalized=True
        )

    # ------------------------------------------------------------
    # Metrics
    # ------------------------------------------------------------

    rows = []

    for name, column in [
        ("random", "s_random"),
        ("non-personalized", "s_global"),
        ("personalized", "s_personal"),
    ]:

        scored = table.dropna(
            subset=[column]
        )

        if (
            len(scored) > 0
            and
            scored.edited.nunique() > 1
        ):

            auc = roc_auc_score(
                scored.edited,
                scored[column]
            )

        else:

            auc = np.nan

        precision, recall, ndcg = (
            doc_metrics(
                scored,
                column
            )
        )

        rows.append(
            {
                "model":
                    name,

                "n_sentences":
                    len(scored),

                "AUROC":
                    auc,

                f"P@{TOP_K}":
                    precision,

                f"Recall@{TOP_K}":
                    recall,

                f"NDCG@{TOP_K}":
                    ndcg,
            }
        )

    return (
        pd.DataFrame(rows),
        table
    )


# ================================================================
# 14. PARTICIPANT PROFILES
# ================================================================

def participant_profiles(
    tab
):

    profiles = {
        pid:
            make_profile(group)

        for pid, group
        in tab.groupby("pid")
    }

    return pd.DataFrame(
        profiles
    ).T


# ================================================================
# 15. EDITOR ARCHETYPES
# ================================================================

def cluster_editors(
    profiles,
    k=3
):

    if len(profiles) == 0:
        return pd.DataFrame()

    k = min(
        k,
        len(profiles)
    )

    if k < 2:
        return profiles.copy()

    X = StandardScaler().fit_transform(
        profiles.fillna(0)
    )

    labels = KMeans(
        n_clusters=k,
        n_init=10,
        random_state=0
    ).fit_predict(X)

    clustered = profiles.copy()

    clustered["cluster"] = labels

    return (
        clustered
        .groupby("cluster")
        .mean()
        .round(3)
    )


# ================================================================
# 16. RECOMMENDATION API
# ================================================================

def recommend(
    draft_text,
    user_profile,
    model,
    top_k=5
):
    """
    Rank sentences in a NEW LLM draft by
    P(user would edit this sentence).
    """

    sentences = split_sentences(
        draft_text
    )

    if not sentences:
        return []

    rows = []

    for i, sentence in enumerate(
        sentences
    ):

        row = {
            "sentence":
                sentence,

            "rel_pos":
                i /
                max(
                    len(sentences) - 1,
                    1
                ),
        }

        row.update(
            stats_of(
                sentence
            )
        )

        row.update(
            user_profile
        )

        rows.append(row)

    table = pd.DataFrame(
        rows
    )

    table["score"] = predict(
        model,
        table,
        personalized=True
    )

    output = []

    for _, row in (
        table
        .sort_values(
            "score",
            ascending=False
        )
        .head(top_k)
        .iterrows()
    ):

        reasons = []

        if (
            row.n_dash
            and
            row.prof_em_dash_removed > 0.05
        ):
            reasons.append(
                "em_dash_removed"
            )

        if (
            row.n_uncontr
            and
            row.prof_contraction_added > 0.05
        ):
            reasons.append(
                "contraction_added"
            )

        if (
            row.ai_hits
            and
            row.prof_ai_word_removed > 0.02
        ):
            reasons.append(
                "ai_word_removed"
            )

        if (
            row.long_frac > 0.10
            and
            row.prof_simplified_words > 0.05
        ):
            reasons.append(
                "simplified_words"
            )

        if (
            row.n_words
            >=
            LONG_SENTENCE_WORDS
            and
            row.prof_shortened > 0.05
        ):
            reasons.append(
                "shortened"
            )

        if (
            row.fp == 0
            and
            row.prof_first_person_added > 0.05
        ):
            reasons.append(
                "first_person_added"
            )

        if reasons:

            suggestions = [
                SUGGESTION[
                    reason
                ]
                for reason in reasons
            ]

        else:

            suggestions = [
                SUGGESTION[
                    "rewritten"
                ]
            ]

        output.append(
            {
                "score":
                    round(
                        float(
                            row.score
                        ),
                        3
                    ),

                "sentence":
                    row.sentence,

                "suggestions":
                    suggestions,
            }
        )

    return output


# ================================================================
# 17. MAIN
# ================================================================

def main():

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--data",
        default="dataset",
        help="Folder containing participant JSON files"
    )

    parser.add_argument(
        "--out",
        default="results_b",
        help="Output folder"
    )

    # ------------------------------------------------------------
    # IMPORTANT:
    # Lexicon is REQUIRED because B.py creates it.
    # ------------------------------------------------------------

    parser.add_argument(
        "--lexicon",
        required=True,
        help=(
            "Path to ai_lexicon.txt generated by B.py"
        )
    )

    args, _ = parser.parse_known_args()

    os.makedirs(
        args.out,
        exist_ok=True
    )

    # ============================================================
    # LOAD DATA-DRIVEN LEXICON
    # ============================================================

    if not os.path.exists(
        args.lexicon
    ):

        raise FileNotFoundError(
            f"\nAI lexicon not found:\n"
            f"{args.lexicon}\n\n"
            f"Run B.py first and make sure "
            f"ai_lexicon.txt exists."
        )

    with open(
        args.lexicon,
        "r",
        encoding="utf-8"
    ) as f:

        AI_LEXICON.update(
            line.strip().lower()
            for line in f
            if line.strip()
        )

    if not AI_LEXICON:

        raise RuntimeError(
            "ai_lexicon.txt is empty."
        )

    print(
        "Loaded data-driven LLM lexicon:",
        len(AI_LEXICON),
        "words"
    )

    # ============================================================
    # LOAD TREATMENT PAIRS
    # ============================================================

    pairs = load_pairs(
        args.data
    )

    if pairs.empty:

        raise RuntimeError(
            f"No valid treatment pairs found "
            f"in {args.data}.\n"
            f"Check the dataset path and JSON structure."
        )

    print(
        "Participants:",
        pairs.pid.nunique(),
        "| draft/final pairs:",
        len(pairs)
    )

    # ============================================================
    # BUILD SENTENCE TABLE
    # ============================================================

    sentence_table, substitutions = (
        build_sentence_table(
            pairs
        )
    )

    if sentence_table.empty:

        raise RuntimeError(
            "Sentence table is empty."
        )

    print(
        f"Draft sentences: "
        f"{len(sentence_table)} "
        f"| edited: "
        f"{sentence_table.edited.sum()} "
        f"({sentence_table.edited.mean():.1%})"
    )

    # ============================================================
    # SAVE SENTENCE TABLE
    # ============================================================

    sentence_table.to_csv(
        os.path.join(
            args.out,
            "B_sentence_table.csv"
        ),
        index=False
    )

    # ============================================================
    # SAVE TOP SUBSTITUTIONS
    # ============================================================

    substitution_df = pd.DataFrame(
        [
            (
                draft,
                final,
                count
            )

            for (
                draft,
                final
            ), count

            in substitutions.most_common(200)
        ],

        columns=[
            "draft",
            "final",
            "count"
        ]
    )

    substitution_df.to_csv(
        os.path.join(
            args.out,
            "B_top_substitutions.csv"
        ),
        index=False
    )

    # ============================================================
    # EDIT-TYPE STATISTICS
    # ============================================================

    print(
        "\nEdit-type rates "
        "(share of draft sentences):"
    )

    print(
        sentence_table[
            [
                f"et_{edit_type}"
                for edit_type in EDIT_TYPES
            ]
        ]
        .mean()
        .round(3)
        .to_string()
    )

    # ============================================================
    # USER PROFILES
    # ============================================================

    profiles = participant_profiles(
        sentence_table
    )

    profiles.to_csv(
        os.path.join(
            args.out,
            "B_user_profiles.csv"
        )
    )

    # ============================================================
    # EDITOR ARCHETYPES
    # ============================================================

    archetypes = cluster_editors(
        profiles
    )

    print(
        "\nEditor archetypes "
        "(cluster means):"
    )

    print(
        archetypes.to_string()
    )

    # ============================================================
    # PARTICIPANT-DISJOINT EVALUATION
    # ============================================================

    participant_metrics, _ = (
        evaluate_participant_disjoint(
            sentence_table
        )
    )

    print(
        "\nPARTICIPANT-DISJOINT EVALUATION"
    )

    print(
        participant_metrics
        .round(3)
        .to_string(index=False)
    )

    participant_metrics.to_csv(
        os.path.join(
            args.out,
            "B_evaluation_participant_disjoint.csv"
        ),
        index=False
    )

    # ============================================================
    # WARM-START PERSONALIZATION EVALUATION
    # ============================================================

    warm_metrics, _ = (
        evaluate_warm_start(
            sentence_table
        )
    )

    print(
        "\nWARM-START PERSONALIZATION EVALUATION"
    )

    print(
        warm_metrics
        .round(3)
        .to_string(index=False)
    )

    warm_metrics.to_csv(
        os.path.join(
            args.out,
            "B_evaluation_warm_start.csv"
        ),
        index=False
    )

    # ============================================================
    # FINAL MODEL
    # ============================================================

    # For the final recommendation system,
    # use all available data.

    full = attach_profiles(
        sentence_table
    )

    final_model = fit_model(
        full,
        personalized=True
    )

    import joblib

    joblib.dump(
        final_model,
        os.path.join(
            args.out,
            "B_model.joblib"
        )
    )

    # ============================================================
    # DEMO
    # ============================================================

    # Use first participant/document as demonstration.
    # IMPORTANT:
    # The demo document itself is excluded from the profile.

    demo_user = pairs.pid.iloc[0]

    demo_doc = pairs.doc_id.iloc[0]

    history = sentence_table[
        (sentence_table.pid == demo_user)
        &
        (sentence_table.doc_id != demo_doc)
    ]

    demo_profile = make_profile(
        history
    )

    demo_draft = pairs.draft.iloc[0]

    recommendations = recommend(
        demo_draft,
        demo_profile,
        final_model,
        top_k=3
    )

    print(
        "\nDEMO recommendations "
        "for a new draft:"
    )

    for recommendation in recommendations:

        print(
            recommendation["score"],
            "|",
            recommendation[
                "sentence"
            ][:90],
            "->",
            recommendation[
                "suggestions"
            ]
        )


# ================================================================
# ENTRY POINT
# ================================================================

if __name__ == "__main__":
    main()